language: python
os:
- linux
python:
- 2.7

addons:
  apt:
    packages:
    - python-setuptools
    - pandoc

script:
- pytest --mpl

install:
- python -m pip install -q --upgrade pip packaging setuptools wheel setuptools_scm
- python -m pip install -q --no-cache-dir -e .[complete]
